### ISSUE TITLE
Functional tests sometimes fail

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-juju-backup-all#26]
Sometimes(Especially when running as part of Release to Edge workflow), the functional tests fail. The `mysql` application gets stuck on `blocked` with status `Cluster is inaccessible from this instance`. This looks like a race condition since it doesn't occur everytime.
We need to fix this and make the tests more predictable.

**Comment by aieri** [comment]
not observed recently, and we've changed how the release workflow works. I'll close for now, we can reopen if it happens again
